# Generated by Django 2.2.6 on 2019-10-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20191019_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersubmission',
            name='quiz',
            field=models.ForeignKey(default='uf3df7d37dee4d202', on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='quiz.Quiz'),
        ),
    ]
