# Generated by Django 2.2.6 on 2019-10-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answersubmission_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersubmission',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='quiz.Quiz'),
        ),
    ]
